mybatis:
#    type-aliases-package: com.fat.display.*Mapper
#    type-handlers-package:
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/mydb"
    username: fat
    password: ps
    spring.datasource.driver-class-name: org.postgresql.Driver
